list = ['word', 'print', 'snick', 'other', 'game', 'white', 'milk', 'future', 'want', 'pilot', 'orange', 'yellow',
        'usually', 'both', 'become', 'grapefruit', 'teach', 'fruit', 'bike', 'station', 'underground', 'hour', 'take',
        'letter', 'always', 'lake', 'beach', 'enjoy', 'sunshine', 'sun', 'year', 'know', 'outing', 'hill', 'find',
        'diamond', 'room', 'life', 'their', 'bedroom', 'kitchen', 'think', 'hole', 'funny', 'hat', 'interesting',
        'never', 'favourite', 'apple', 'pear', 'pack', 'peach', 'strawberry', 'papaya', 'answer', 'robot', 'bilberry',
        'berry', 'core', 'ginkgo', 'tissue', 'chestnut', 'hickory', 'hello', 'foot', 'car', 'fun', 'tea', 'guess',
        'you', 'what', 'name', 'python', 'goodbye', 'hi', 'if', 'break', 'rainbow', 'blue', 'red', 'green', 'city',
        'number', 'list', 'map', 'hot', 'black', 'juice', 'in', 'on', 'under', 'lunch', 'pink', 'anteater', 'chat',
        'work', 'yes', 'duck', 'translate', 'turtle', 'maths', 'mineral', 'iron', 'stone', 'uranium', 'coal', 'gold',
        'hematite', 'calcite', 'amethyst', 'marble', 'alloy', 'magnetite', 'pyrite', 'sulfur', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '']
