import time

import pyautogui

p = pyautogui
p.moveTo(208, 744)
pyautogui.scroll(300)
p.moveTo(100, 111)
p.rightClick()
p.moveTo(110, 111)
p.click()
p.moveTo(400, 211)
p.click()
screen_width, screen_height = pyautogui.size()
center_x, center_y = screen_width // 2, screen_height // 2
pyautogui.moveTo(center_x, center_y)
p.click()
p.write('turtle.auto')
p.press('enter')
p.press('enter', presses=0, interval=0)
p.moveTo(1691, 680)
p.click()
p.moveTo(860, 920)
p.click()
p.press('enter')
p.press('enter', presses=0, interval=0)
p.write('import')
p.press('space')
p.press('space', presses=0, interval=0)
p.write('turtle')
p.press('enter')
p.press('enter', presses=0, interval=0)
p.press('enter')
p.press('enter', presses=0, interval=0)
p.write("turtle.bgcolor('pink')\n")
p.write("turtle.pensize(2)\n")
p.write("turtle.speed(1000)\n")
p.write("for i in range(100):\n")
p.press('tab')
p.press('tab', presses=0, interval=0)
p.write("turtle.pencolor('yellow')\n")
p.write('turtle.forward(100)\n')
p.write('turtle.left(95)')
p.moveTo(1272, 43)
p.click()
p.moveTo(1275, 1097)
time.sleep(8)
p.click()
p.click()
p.moveTo(95, 1020)
p.rightClick()
p.moveTo(165, 690)
p.click()
p.moveTo(926, 620)
p.click()
p.moveTo(1691, 680)
p.click()
p.hotkey('command', 'fn', 'f2')
